use adharshdb;
select * from customers limit 10;

SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'CUSTOMERS';
SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS ;

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'CUSTOMERS';